# Generated by Django 5.1.2 on 2024-10-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('cid', models.CharField(max_length=20, primary_key='cid', serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobilenumber', models.IntegerField()),
                ('age', models.IntegerField()),
                ('accountno', models.IntegerField()),
            ],
        ),
    ]
